### ISSUE TITLE
When `FindFilesWithPattern` fails with `STATUS_NOT_IMPLEMENTED`, `DispatchDirectoryInformation` returns the first entry from `FindFiles`

### ISSUE THREAD

**Issue by inetic** [dokan-dev/dokany#1149]
# Environment
 * Windows version: 10 
 * Processor architecture: Core i5 3210M 
 * Dokany version: [5464da7](https://github.com/dokan-dev/dokany/tree/5464da7187cf1a3fb05977df28c1da98087051c5) - the one currently used by [dokan-rust](https://github.com/dokan-dev/dokan-rust/tree/d88cbf15d681b37b4cb5cd5e79f0f90d877219b5).
 * Library type (Dokany/FUSE): Found this issue while using dokan-rust, but it's likely a problem in Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
When the `FindFilesWithPattern` is set to _non_-`NULL` but fails with `STATUS_NOT_IMPLEMENTED`, the code in `DispatchDirectoryInformation` will go on to use `FindFiles` [here](https://github.com/dokan-dev/dokany/blob/f225a0d60a1dc3d3656ccef3c6c99401ac66a20b/dokan/directory.c#L709).

If `IoEvent->EventContext->Operation.Directory.SearchPatternLength` is set, then the assumption is that the output from `FindFiles` shall be filtered in `MatchFiles` (going from [`DispatchDirectoryInformation`](https://github.com/dokan-dev/dokany/blob/f225a0d60a1dc3d3656ccef3c6c99401ac66a20b/dokan/directory.c#L717) > [`EndFindFilesCommon`](https://github.com/dokan-dev/dokany/blob/f225a0d60a1dc3d3656ccef3c6c99401ac66a20b/dokan/directory.c#L569) > [`WriteDirectoryResults`](https://github.com/dokan-dev/dokany/blob/f225a0d60a1dc3d3656ccef3c6c99401ac66a20b/dokan/directory.c#L526) > [`MatchFiles`](https://github.com/dokan-dev/dokany/blob/f225a0d60a1dc3d3656ccef3c6c99401ac66a20b/dokan/directory.c#L397)).

Now in `MatchFiles`, because `FindFilesWithPattern` is _non_-`NULL`, the variable `patternCheck` is **not** set to `TRUE` [here](https://github.com/dokan-dev/dokany/blob/f225a0d60a1dc3d3656ccef3c6c99401ac66a20b/dokan/directory.c#L406). That means that [this `if` condition](https://github.com/dokan-dev/dokany/blob/f225a0d60a1dc3d3656ccef3c6c99401ac66a20b/dokan/directory.c#L416) always succeeds and the function returns whatever was the first entry returned by `FindFiles` (as opposed to the first entry that matches the `pattern`.

I first encountered the issue while trying to use the `dokan-rust` package and reported the issue [there](https://github.com/dokan-dev/dokan-rust/issues/6) together with steps to reproduce it with the `memfs` example.

**Comment by inetic** [comment]
My knee-jerk fix would be to keep a flag of whether `FindFilesWithPatter` returned `STATUS_NOT_IMPLEMENTED` and pass that information from `DispatchDirectoryInformation` all the way to `MatchFiles`. But perhaps there is a better way.

**Comment by Liryna** [comment]
Hi @inetic ,

Thank you for the report and the guidance how to fix it. Very impressive for catching this 💪 

I have implemented your fix by using a BOOLEAN in the context of the open as the result of the FindFiles could be requery if needed
https://github.com/dokan-dev/dokany/commit/0e6dc66c598bb1cfeb21d4cecacdf4ec12e6154d

Let me know what you think !

**Comment by inetic** [comment]
Thank you @Liryna, this looks good to me.

**Comment by KoltesDigital** [comment]
@inetic Thanks for the finding!

@Liryna Would you release a new patch version? So that language bindings could be released as well.

**Comment by Liryna** [comment]
I would like but I am facing some difficulty to get an EV Certificate right now to do the release. It might take some time...

**Comment by hamflx** [comment]
The latest version v2.0.6.1000 still doesn't seem to include this patch. https://github.com/dokan-dev/dokany/blob/v2.0.6.1000/dokan/directory.c#L701-L706
